apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
   ingress_type: ingress
   ingress_tls_secret: awx-secret-tls
   hostname: awx.localt.st
   projects_persistence: true
   projects_storage_access_mode: ReadWriteOnce
